sudo: false
language: node_js
node_js:
  - '10.16.0'
script:
  - pnpm run build && pnpm run test:ci
after_script:
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
cache:
  directories:
    - /home/travis/.pnpm-store
